name: ⚖️ Register Validator
description: Submit a request to register your validator node in the genesis of an Axone network.
title: "⚖️ Register Validator: "
labels: ["register-validator"]
assignees:
  - amimart
  - ccamel
  - tpelliet
  - botanik
body:
  - type: dropdown
    id: network
    attributes:
      label: Network Choice
      description: Choose the Axone network you want to join
      multiple: false
      options:
        - drunemeton-1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Who are you?
      description: Free space to talk a little bit about you, as a Validator.
  - type: textarea
    id: delegator_addr
    attributes:
      label: Delegator address
      description: Your delegator address, the one you used to sign the gentx.
    validations:
      required: true
  - type: textarea
    id: gentx
    attributes:
      label: gentx
      description: The gentx transaction to be integrated in the corresponding genesis, in json format.
      placeholder: |
        {
          "type":"auth/StdTx",
          "value":{
              ...
          }
        }
      render: json
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        🙏 Thanks for your interest in Axone, for now we can let [botanik](https://github.com/bot-anik) take care of the technical part of your request before entering the review process.
